
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Use environment variables or build-time constants for production
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://pkxvaddvdzeamhqvxvks.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBreHZhZGR2ZHplYW1ocXZ4dmtzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNzAzMTksImV4cCI6MjA2NTc0NjMxOX0.8susiDGXFIcX8Wt41Y9-LLwdHjaasoPy3se3dBNpLUI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
